Repository ProjectTing/Ting, pull requests merged in 2025-02, with the labels that each got.

#74 Refactor: 게시글 리스트, 작성, 네트워킹 MVVM+Rx 적용
  Ting/API/PostService.swift
  Ting/CustomView/LabelAndTagStackView.swift
  Ting/Post/PostView/FindMemberUploadVC.swift
  Ting/Post/PostView/FindTeamUploadVC.swift
  Ting/Post/PostView/FindTeamUploadView.swift
  Ting/Post/PostView/PostListVC.swift
  Ting/Post/PostViewModel/FindMemberUploadVM.swift
  Ting/Post/PostViewModel/FindTeamUploadVM.swift
  Ting/Post/PostViewModel/PostListVM.swift
Labels: refactor

#78 Refactor : MVVM 적용전 코드로 원상복구
  Ting.xcodeproj/project.pbxproj
  Ting/Models/ReportModel.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/ReportVC.swift
  Ting/Post/PostViewModel/ReportViewModel.swift
Labels: Warning, refactor

#79 Refactor: 게시글 작성, 리스트 MVVM 패턴 적용 전으로
  Ting/API/PostService.swift
  Ting/CustomView/LabelAndTagStackView.swift
  Ting/Post/PostView/FindMemberUploadVC.swift
  Ting/Post/PostView/FindMemberUploadView.swift
  Ting/Post/PostView/FindTeamUploadVC.swift
  Ting/Post/PostView/FindTeamUploadView.swift
  Ting/Post/PostView/PostListVC.swift
  Ting/Post/PostViewModel/FindMemberUploadVM.swift
  Ting/Post/PostViewModel/FindTeamUploadVM.swift
  Ting/Post/PostViewModel/PostListVM.swift
Labels: Warning, refactor

#81 Fix: 임시 빌드처리
  Ting/Post/PostView/PostListVC.swift
  Ting/Search/SearchView/SearchVC.swift
Labels: Warning

#84 Feat: 애플 로그인 파이어 베이스 연결 및 기능 구현
  Ting.xcodeproj/project.pbxproj
  Ting/SignUp/SignUpView/PermissionVC.swift
  Ting/SignUp/SignUpView/PermissionView.swift
  Ting/SignUp/SignUpView/SignUpView.swift
  Ting/SignUp/SignUpView/SignUpViewController.swift
  Ting/SignUp/SignUpView/TermsCell.swift
  Ting/SignUp/SignUpView/TermsModalVC.swift
  Ting/SignUp/SignUpView/TermsView.swift
  Ting/SignUp/SignUpView/TermsViewController.swift
  Ting/Ting.entitlements
Labels: implement, feat

#87 Refactor: 탭바 리팩토링, 아이콘 변경, 텍스트 변경
  Ting/TabBar/TabBar.swift
Labels: feat, refactor

#89 Feat : ReportVC 파이어베이스 연동
  Ting/Models/Post.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/ReportVC.swift
Labels: feat, Test

#95 Feat : ReportVC 제약조건 추가 / Refactor : UploadVC에 맞게 수정
  Ting/API/ReportManager.swift
  Ting/Models/Post.swift
  Ting/Models/Report.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/ReportVC.swift
Labels: Warning, refactor

#97 Feat : ListVC -> DetailVC데이터 연동 + DetailVC-> UploadVC 데이터 연동
  Ting/API/PostService.swift
  Ting/CustomView/LabelAndTagSection.swift
  Ting/Post/PostView/JoinTeamUploadVC.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/PostListVC.swift
  Ting/Post/PostView/RecruitMemberUploadVC.swift
Labels: implement, feat

#99 Feat: 약관 동의, 회원가입 완료 후 탭바로 이동
  Ting/SignUp/SignUpView/PermissionView.swift
  Ting/SignUp/SignUpView/SignUpViewController.swift
  Ting/SignUp/SignUpView/TermsCell.swift
  Ting/SignUp/SignUpView/TermsModalVC.swift
Labels: implement, feat

#101 Feat: 게시글리스트 페이징 기능 구현
  Ting/API/PostService.swift
  Ting/CustomView/LoadingFooterView.swift
  Ting/Post/PostView/PostListVC.swift
  Ting/Post/PostView/PostListView.swift
Labels: feat

#106 Feat: 루트 뷰 컨트롤러 조정 및 구현
  Ting/AppDelegate.swift
  Ting/SceneDelegate.swift
  Ting/SignUp/SignUpView/SignUpViewController.swift
Labels: implement

#104 Feat : DetailVC 추가기능 구현
  Ting/API/PostService.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/PostListVC.swift
Labels: implement, feat

#108 Refactor: 회원정보 추가 뷰 수정
  Ting/API/UserInfoService.swift
  Ting/Models/UserInfo.swift
  Ting/MyPage/AddUserInfo/AddUserInfoVC.swift
  Ting/MyPage/DeleteInfo/DeleteInfoVC.swift
  Ting/MyPage/EditInfo/EditCustomView.swift
  Ting/MyPage/EditInfo/EditInfoVC.swift
  Ting/MyPage/MyPageMain/MyPageCustomVIew.swift
  Ting/MyPage/MyPageMain/MyPageMainVC.swift
  Ting/TabBar/TabBar.swift
Labels: implement, feat, refactor

#112 Feat: 회원 탈퇴시 데이터 삭제 구현
  Ting/MyPage/DeleteInfo/DeleteInfoVC.swift
  Ting/SignUp/SignUpView/SignUpViewController.swift
Labels: implement, feat

#113 Feat : SignUpViewController 새로운 고유구별값 적용 및 회원가입, 정보기입시 적용
  Ting/Models/UserInfo.swift
  Ting/MyPage/AddUserInfo/AddUserInfoVC.swift
  Ting/SceneDelegate.swift
  Ting/SignUp/SignUpView/SignUpViewController.swift
Labels: implement, feat

#115 Feat: 검색기능 구현 및 추가수정
  Ting/API/PostService.swift
  Ting/CustomView/BaseUploadView.swift
  Ting/CustomView/LabelAndTagSection.swift
  Ting/CustomView/LabelAndTextField.swift
  Ting/CustomView/PaddingLabel.swift
  Ting/Models/Post.swift
  Ting/Post/PostView/JoinTeamUploadVC.swift
  Ting/Post/PostView/JoinTeamUploadView.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/PostListVC.swift
  Ting/Post/PostView/RecruitMemberUploadVC.swift
  Ting/Post/PostView/RecruitMemberUploadView.swift
  Ting/Post/PostView/ReportVC.swift
  Ting/Search/SearchView/SearchResultVC.swift
  Ting/Search/SearchView/SearchSelectModal.swift
  Ting/Search/SearchView/SearchSelectModalVC.swift
  Ting/Search/SearchView/SearchVC.swift
  Ting/Search/SearchView/SearchView.swift
Labels: feat

#116 Feat : 닉네임 중복검증 적용
  Ting/API/UserInfoService.swift
  Ting/MyPage/AddUserInfo/AddUserInfoVC.swift
  Ting/MyPage/DeleteInfo/DeleteInfoVC.swift
  Ting/MyPage/EditInfo/EditInfoVC.swift
  Ting/SceneDelegate.swift
  Ting/SignUp/SignUpView/PermissionVC.swift
  Ting/SignUp/SignUpView/PermissionView.swift
  Ting/SignUp/SignUpView/SignUpViewController.swift
  Ting/SignUp/SignUpView/TermsModalVC.swift
Labels: implement, feat

#117 Feat: 마이페이지 UI 대응, Firebase R 구현
  Ting.xcodeproj/project.pbxproj
  Ting/API/UserInfoService.swift
  Ting/MyPage/AddUserInfo/AddUserInfoVC.swift
  Ting/MyPage/MyPageMain/MyPageCustomVIew.swift
  Ting/MyPage/MyPageMain/MyPageMainVC.swift
Labels: implement, feat

#121 Feat: 리스트 새로고침, 글 작성 후 새로고침 기능 구현
  Ting/API/PostService.swift
  Ting/Extension/DateFormatter.swift
  Ting/Post/PostEnum.swift
  Ting/Post/PostView/JoinTeamUploadVC.swift
  Ting/Post/PostView/PostListVC.swift
  Ting/Post/PostView/RecruitMemberUploadVC.swift
  Ting/Search/SearchView/SearchVC.swift
Labels: implement, feat

#123 Fix: Navigation Bar 출력 안되는 문제 긴급 수정
  Ting/MyPage/MyPageMain/MyPageMainVC.swift
Labels: Warning

#124 Feat: Ting 앱 약관 작성 및 구현
  Ting/SignUp/SignUpView/SignUpVC.swift
  Ting/SignUp/SignUpView/TermsCell.swift
  Ting/SignUp/SignUpView/TermsModalVC.swift
Labels: implement, feat, refactor

#131 Feat : 각 뷰간 nickname 데이터 객체 이동 / 수정시 바로 업데이트 기능 구현 / detailVC 불필요 라벨 제거
  Ting/API/PostService.swift
  Ting/Post/PostView/JoinTeamUploadVC.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/PostListVC.swift
  Ting/Post/PostView/RecruitMemberUploadVC.swift
  Ting/Post/PostView/ReportVC.swift
  Ting/SignUp/SignUpView/SignUpVC.swift
Labels: implement, feat

#130 Feat: 회원탈퇴시 애플 재인증 추가, 프로젝트 지원설정
  Ting.xcodeproj/project.pbxproj
  Ting/MyPage/DeleteInfo/DeleteInfoVC.swift
Labels: feat

#135 Feat: 회원정보 수정 구현 완료
  Ting/API/UserInfoService.swift
  Ting/Models/UserInfo.swift
  Ting/MyPage/AddUserInfo/AddUserInfoVC.swift
  Ting/MyPage/EditInfo/EditCustomView.swift
  Ting/MyPage/EditInfo/EditInfoVC.swift
  Ting/MyPage/MyPageMain/MyPageMainVC.swift
Labels: implement, feat

#138 Fix: TabBar 팀원 모집 아이콘 변경
  Ting/TabBar/TabBar.swift
Labels: implement, refactor

#139 Feat: 동일한 계정으로 로그인 시 TabBar로 이동
  Ting/MyPage/DeleteInfo/DeleteInfoVC.swift
  Ting/SceneDelegate.swift
Labels: implement, feat

#140 Refactor, Cmt: 주석 수정 및 중복로직 삭제
  Ting/API/PostService.swift
  Ting/CustomView/TagFlowLayout.swift
  Ting/Post/PostView/JoinTeamUploadVC.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/RecruitMemberUploadVC.swift
  Ting/Post/PostView/ReportVC.swift
Labels: refactor

#142 Refactor: UI 통일 및 수정
  Ting/API/PostService.swift
  Ting/Assets/Assets.xcassets/accent.colorset/Contents.json
  Ting/Assets/Assets.xcassets/background.colorset/Contents.json
  Ting/Assets/Assets.xcassets/brownText.colorset/Contents.json
  Ting/Assets/Assets.xcassets/deepCocoa.colorset/Contents.json
  Ting/Assets/Assets.xcassets/grayCloud.colorset/Contents.json
  Ting/Assets/Assets.xcassets/grayText.colorset/Contents.json
  Ting/Assets/Assets.xcassets/ivoryWhite.colorset/Contents.json
  Ting/Assets/Assets.xcassets/primary.colorset/Contents.json
  Ting/Assets/Assets.xcassets/secondary.colorset/Contents.json
  Ting/Extension/HexColorCode.swift
  Ting/Main/MainView/HeaderView.swift
  Ting/Main/MainView/MainVC.swift
  Ting/Main/MainView/MainViewCell.swift
  Ting/MyPage/DeleteInfo/DeleteInfoVC.swift
  Ting/MyPage/EditInfo/EditCustomView.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/PostListVC.swift
  Ting/Post/PostView/PostListView.swift
  Ting/Post/PostView/ReportVC.swift
  Ting/Search/SearchView/SearchVC.swift
  Ting/Search/SearchView/SearchView.swift
Labels: implement, refactor

#146 Feat: 로그아웃 기능 구현
  Ting/MyPage/MyPageMain/MyPageMainVC.swift
Labels: implement, feat

#147 Fix: 서치뷰 오토레이아웃 수정
  Ting/Search/SearchView/SearchSelectModalVC.swift
  Ting/Search/SearchView/SearchVC.swift
  Ting/Search/SearchView/SearchView.swift
Labels: refactor

#148 Fix: 검색관련 수정
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Search/SearchView/SearchVC.swift
Labels: Warning

#155 Feat : 닉네임 변경시 Posts에 저장된 닉네임도 같이 변경
  Ting/API/UserInfoService.swift
Labels: implement, feat

#158 Feat : 회원정보 수정시 신고자, 신고작성자 닉네임 변경
  Ting/API/ReportManager.swift
  Ting/API/UserInfoService.swift
Labels: implement, feat

#163 Feat: 앱 플로우 수정
  Ting/MyPage/DeleteInfo/DeleteInfoVC.swift
  Ting/SceneDelegate.swift
  Ting/SignUp/SignUpView/PermissionVC.swift
  Ting/SignUp/SignUpView/SignUpVC.swift
Labels: feat, refactor

#165 Fix: 작성,수정시 게시글리스트 새로고침 delegate 추가, UI 일부 수정
  Ting/CustomView/CustomTag.swift
  Ting/Main/MainView/MainVC.swift
  Ting/Post/PostView/JoinTeamUploadVC.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/PostListVC.swift
  Ting/Post/PostView/RecruitMemberUploadVC.swift
Labels: fix

#166 Feat: 비회원 로그인 구현
  Ting/MyPage/DeleteInfo/DeleteInfoVC.swift
  Ting/MyPage/MyPageMain/MyPageMainVC.swift
  Ting/SceneDelegate.swift
  Ting/SignUp/SignUpView/SignUpVC.swift
  Ting/SignUp/SignUpView/SignUpView.swift
Labels: implement, feat

#168 Fix : 수정하기 연속진행시 안되던 부분수정, 닉네임 수정하기 안먹히던 현상 수정
  Ting/API/PostService.swift
  Ting/MyPage/EditInfo/EditInfoVC.swift
  Ting/Post/PostView/PostDetailVC.swift
Labels: fix

#170 Feat: 비로그인 체크, 알럿 구현 / 메인셀 클릭 시 유저체크
  Ting/Extension/BasicAlert.swift
  Ting/Extension/LoginCheck+Alert.swift
  Ting/Main/MainView/MainVC.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/PostListVC.swift
  Ting/TabBar/TabBar.swift
Labels: feat

#172 Fix: 수정하기 버튼타이틀, 탈퇴시 UserDefaults 삭제, 비회원 화면이동 수정
  Ting/Extension/LoginCheck+Alert.swift
  Ting/MyPage/DeleteInfo/DeleteInfoVC.swift
  Ting/Post/PostView/JoinTeamUploadVC.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/PostListVC.swift
  Ting/Post/PostView/RecruitMemberUploadVC.swift
Labels: fix

#175 Fix: 컬러에셋 일부 이름 변경
  Ting/Assets/Assets.xcassets/primaries.colorset/Contents.json
  Ting/Assets/Assets.xcassets/secondaries.colorset/Contents.json
  Ting/CustomView/BaseUploadView.swift
  Ting/CustomView/CustomTag.swift
  Ting/CustomView/LabelAndTagSection.swift
  Ting/Main/MainView/MainVC.swift
  Ting/Main/MainView/MainViewCell.swift
  Ting/MyPage/AddUserInfo/AddUserInfoVC.swift
  Ting/MyPage/DeleteInfo/DeleteInfoVC.swift
  Ting/MyPage/EditInfo/EditCustomView.swift
  Ting/MyPage/EditInfo/EditInfoVC.swift
  Ting/MyPage/MyPageMain/MyPageMainVC.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/PostListVC.swift
  Ting/Post/PostView/ReportVC.swift
  Ting/Search/SearchView/SearchSelectModal.swift
  Ting/Search/SearchView/SearchVC.swift
  Ting/Search/SearchView/SearchView.swift
  Ting/SignUp/SignUpView/PermissionView.swift
  Ting/SignUp/SignUpView/SignUpView.swift
  Ting/TabBar/TabBar.swift
Labels: Warning, refactor, fix

#178 Fix: Hierarchy 경고문 삭제(카드뷰 그림자 관련), 마이페이지 색상변경 버그 픽스
  Ting/MyPage/AddUserInfo/AddUserInfoVC.swift
  Ting/MyPage/DeleteInfo/DeleteInfoVC.swift
  Ting/MyPage/EditInfo/EditInfoVC.swift
  Ting/MyPage/MyPageMain/MyPageMainVC.swift
Labels: fix

#182 Fix: 경고문 삭제 (OAuth 인증 구조)
  Ting/SignUp/SignUpView/SignUpVC.swift
  Ting/SignUp/SignUpView/TermsModalVC.swift
Labels: fix

#181 Fix : DetailVC, ReportVC 경고문 삭제
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/ReportVC.swift
Labels: fix

#184 Fix: 에러처리 일부수정, 스크롤뷰 레이아웃 수정
  Ting/Post/PostView/PostListVC.swift
  Ting/Search/SearchView/SearchView.swift
Labels: fix

#183 Fix : DetailVC 신고하기 버튼 수정
  Ting/Post/PostView/PostDetailVC.swift
Labels: fix

#186 Fix: 신고하기 뷰에서 키보드가 내려가지 않는 문제 해결
  Ting/Post/PostView/ReportVC.swift
Labels: Warning, fix

#188 Feat: 회원탈퇴 약관 버튼 수정
  Ting/MyPage/DeleteInfo/DeleteInfoVC.swift
Labels: implement

#192 Feat/Fix : DetailVC 뷰 배치 및 디자인 수정 및 조정, ReportVC 신규기능 추가 및 오류수정
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/ReportVC.swift
Labels: feat, fix

#193 Feat: TextField 공백추가, 공백, 특수문자 검사 로직 구현 및 추가
  Ting/Extension/SpacesAndSpecialChar.swift
  Ting/MyPage/AddUserInfo/AddUserInfoVC.swift
  Ting/MyPage/EditInfo/EditCustomView.swift
  Ting/MyPage/EditInfo/EditInfoVC.swift
  Ting/SignUp/SignUpView/SignUpView.swift
Labels: implement, feat

#194 F ix: 검색기능 관련 추가 수정, 게시글 작성 공백입력 제한
  Ting/API/PostService.swift
  Ting/CustomView/LabelAndTextField.swift
  Ting/Post/PostView/JoinTeamUploadVC.swift
  Ting/Post/PostView/RecruitMemberUploadVC.swift
  Ting/Search/SearchView/SearchVC.swift
  Ting/Search/SearchView/SearchView.swift
Labels: feat, fix

#200 Fix : DetailVC 뷰 객체 추가 및 조정
  Ting/Post/PostView/PostDetailVC.swift
Labels: fix

#204 Feat: 앱 아이콘 등록
  Ting.xcodeproj/project.pbxproj
  Ting/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  Ting/Assets/Assets.xcassets/AppIcon.appiconset/TingIcon 1.png
  Ting/Assets/Assets.xcassets/AppIcon.appiconset/TingIcon 2.png
  Ting/Assets/Assets.xcassets/AppIcon.appiconset/TingIcon.png
Labels: fix

#205 🚀 Ver 1.0 앱 아이콘 추가
  Ting.xcodeproj/project.pbxproj
  Ting/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  Ting/Assets/Assets.xcassets/AppIcon.appiconset/TingIcon 1.png
  Ting/Assets/Assets.xcassets/AppIcon.appiconset/TingIcon 2.png
  Ting/Assets/Assets.xcassets/AppIcon.appiconset/TingIcon.png
Labels: fix

#207 Feat : ReportVC 신고하기 버튼 시 infos에 신고데이터 배열 업데이트
  Ting/API/UserInfoService.swift
  Ting/Models/UserInfo.swift
  Ting/Post/PostView/ReportVC.swift
Labels: feat

#209 Feat : 신고하기 버튼 터치시 해당 게시글 안보이게 적용
  Ting/API/PostService.swift
  Ting/API/UserInfoService.swift
Labels: feat

#210 Feat: 차단기능 구현 및 신고기능과 통합
  Ting/API/PostService.swift
  Ting/API/UserInfoService.swift
  Ting/Models/Post.swift
  Ting/Models/UserInfo.swift
  Ting/Post/PostView/JoinTeamUploadVC.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/RecruitMemberUploadVC.swift
  Ting/Post/PostView/ReportVC.swift
Labels: feat

#213 Feat : 신고하기 버튼 터치 시 해당 게시글의 신고하기 횟수 증가 및 5회인 경우에 해당 게시글은 자동 삭제
  Ting/API/PostService.swift
  Ting/Models/Post.swift
  Ting/Post/PostView/JoinTeamUploadVC.swift
  Ting/Post/PostView/RecruitMemberUploadVC.swift
  Ting/Post/PostView/ReportVC.swift
Labels: feat

#215 Feat: 게시글 신고 접수 시, 슬랙으로 메시지를 전송
  Ting/API/SlackService.swift
  Ting/Post/PostView/ReportVC.swift
Labels: implement, feat

#216 Fix: 검색로직수정
  Ting/API/PostService.swift
Labels: fix

#219 Fix: project파일 쪽에서 불필요한 파일로 발생하는 오류 제거
  Ting.xcodeproj/project.pbxproj
Labels: Warning

#220 Fix: APNs 관련 오류 삭제
  Ting.xcodeproj/project.pbxproj
Labels: Warning

#221 Fix: 다크모드 지원x, 기술태크 겹침문제해결
  Ting/Info.plist
  Ting/Post/PostView/PostDetailVC.swift
Labels: Warning, fix

#230 Fix: 키보드 관련 수정, 일부 필드 글자수 변경
  Ting.xcodeproj/project.pbxproj
  Ting/MyPage/AddUserInfo/AddUserInfoVC.swift
  Ting/MyPage/EditInfo/EditCustomView.swift
  Ting/MyPage/EditInfo/EditInfoVC.swift
Labels: fix

#236 Fix : 팀원모집 - 팁 합류간 출력내용 수정
  Ting/Post/PostView/PostDetailVC.swift
Labels: fix

#238 Fix: 게시글 작성, 리스트 1.0.3 피드백 관련 수정
  Ting/API/PostService.swift
  Ting/CustomView/BaseUploadView.swift
  Ting/Post/PostView/JoinTeamUploadVC.swift
  Ting/Post/PostView/JoinTeamUploadView.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/PostListVC.swift
  Ting/Post/PostView/RecruitMemberUploadVC.swift
  Ting/Post/PostView/RecruitMemberUploadView.swift
  Ting/Post/PostView/ReportVC.swift
Labels: feat, fix

#242 Feat: 약관 동의, 약관 URL 이동 수정
  Ting/SignUp/SignUpView/TermsCell.swift
  Ting/SignUp/SignUpView/TermsModalVC.swift
Labels: implement, fix

#247 Feat: 닉네임 이외 텍스트필드 공백, 특수문자 검증 로직 구현
  Ting.xcodeproj/project.pbxproj
  Ting/Extension/SpacesAndSpecialChar.swift
  Ting/MyPage/AddUserInfo/AddUserInfoVC.swift
  Ting/MyPage/EditInfo/EditInfoVC.swift
  Ting/MyPage/MyPageMain/MyPageMainVC.swift
Labels: implement, feat, Warning, fix

#249 Fix: 약관 미동의 후 앱 재접속시 넘어가는 버그 수정
  Ting/SignUp/SignUpView/PermissionVC.swift
  Ting/SignUp/SignUpView/SignUpVC.swift
Labels: fix

#250 Fix: 첫 글자 공백인지만 검증하도록 검증 로직 수정
  Ting/MyPage/AddUserInfo/AddUserInfoVC.swift
  Ting/MyPage/EditInfo/EditInfoVC.swift
Labels: fix

#252 Fix: 로그아웃, 종료 후 약관 동의 데이터 사라지는 버그 수정
  Ting/Main/MainView/MainViewCell.swift
  Ting/SignUp/SignUpView/SignUpVC.swift
Labels: Warning, fix

#254 Chore: Update README.md
  README.md
Labels: fix

#255 Docs: Update README.md
  README.md
Labels: Update

#257 Docs: Update README.md
  README.md
Labels: Update

#258 Docs: Update README.md
  README.md
Labels: Update

#259 Docs: Update README.md
  README.md
Labels: Update

#262 Fix: 신고 발생시 슬랙 알림이 오는 기능 관련 수정
  .gitignore
  Ting.xcodeproj/project.pbxproj
  Ting/API/SlackService.swift
  Ting/MyPage/EditInfo/EditInfoVC.swift
Labels: fix

#265 Docs: Update README.md
  README.md
Labels: Update

#266 Docs: Update README.md
  README.md
Labels: Update

#267 Docs: Update README.md
  README.md
Labels: Update

#268 Update: v1.0.5기준 ReadME 업데이트
  README.md
Labels: Update

#270 Docs: 단위, 통합 테스트 md파일 추가
  integration-test.md
  test-scenarios.md
Labels: feat, Test

#272 Docs: Update README.md
  README.md
Labels: Update
