Repository ProjectTing/Ting, pull requests merged in 2025-01, with the labels that each got.

#6 Feat: 각 역할별 VC 생성
  Ting/Main/MainVC.swift
  Ting/MyPage/DeleteInfoVC.swift
  Ting/MyPage/EditInfoVC.swift
  Ting/MyPage/MyPageMainVC.swift
  Ting/Post/PostDetailVC.swift
  Ting/Post/PostMainVC.swift
  Ting/Post/PostUploadVC.swift
  Ting/Post/ReportVC.swift
  Ting/Search/SearchResultVC.swift
  Ting/Search/SearchVC.swift
Labels: implement

#13 feat: Firebase SDK, info파일 추가
  Ting.xcodeproj/project.pbxproj
  Ting.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Ting/AppDelegate.swift
  Ting/GoogleService-Info.plist
Labels: feat

#22 Feat: 하단 탭바 구현
  Ting/Main/MainVC.swift
  Ting/SceneDelegate.swift
  Ting/Search/SearchVC.swift
  Ting/TabBar/TabBar.swift
Labels: implement

#25 feat: Assets 폴더 생성,
  Ting/Assets/Assets.xcassets/AccentColor.colorset/Contents.json
  Ting/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  Ting/Assets/Assets.xcassets/Contents.json
  Ting/Assets/Fonts/Gemini Moon.otf
  Ting/Assets/UIColorExtension/HexColorCode.swift
  Ting/Main/MainVC.swift
  Ting/Main/MainViewCell.swift
  Ting/SceneDelegate.swift
Labels: feat

#29 Feat: 커스텀 태그, 게시글 작성뷰 구현
  Ting/CustomView/CustomTag.swift
  Ting/Post/PostUploadVC.swift
  Ting/Post/PostUploadView.swift
Labels: implement, feat

#31 Feat: 서치뷰 커스텀 컬러, 태그 적용
  Ting/Search/SearchSelectModal.swift
  Ting/Search/SearchSelectModalVC.swift
  Ting/Search/SearchV.swift
  Ting/Search/SearchVC.swift
  Ting/Search/SearchView.swift
Labels: refactor

#37 Feat: 회원 정보 수정 UI 1차 구현 완료
  Ting/MyPage/DeleteInfoVC.swift
  Ting/MyPage/EditCustomView.swift
  Ting/MyPage/EditInfoVC.swift
  Ting/MyPage/MyPageMainVC.swift
  Ting/TabBar/TabBar.swift
Labels: implement

#41 Feat: 약관 동의 모달 창 구현
  Ting/SignUp/FirstView.swift
  Ting/SignUp/FirstViewController.swift
  Ting/SignUp/SignUpView.swift
  Ting/SignUp/SignUpViewController.swift
  Ting/SignUp/TermsCell.swift
  Ting/SignUp/TermsView.swift
  Ting/SignUp/TermsViewController.swift
Labels: implement, feat

#42 Feat: MyPage, 회원정보 수정, 탈퇴 UI 구현 완료
  Ting/MyPage/DeleteInfoVC.swift
  Ting/MyPage/EditCustomView.swift
  Ting/MyPage/EditInfoVC.swift
  Ting/MyPage/MyPageCustomVIew.swift
  Ting/MyPage/MyPageMainVC.swift
Labels: implement, feat

#46 Feat: 메인페이지 UI 구현
  Ting/Main/MainVC.swift
  Ting/Main/MainViewCell.swift
Labels: implement, feat

#48 Fix: 서치바에서 검색뷰로 이동하지 않는 문제 수정
  Ting/Main/MainVC.swift
Labels: Warning

#49 Feat: FirstView를 PermissionView로 이름 변경
  Ting/SignUp/PermissionVC.swift
  Ting/SignUp/PermissionView.swift
  Ting/SignUp/SignUpView.swift
  Ting/SignUp/SignUpViewController.swift
  Ting/SignUp/TermsCell.swift
  Ting/SignUp/TermsView.swift
Labels: refactor

#52 Feat: 게시글 리스트 UI 1차 구현
  Ting/Post/PostMainVC.swift
  Ting/Post/PostMainView.swift
  Ting/Post/PostUploadView.swift
Labels: implement, feat

#53 Feat: 서치뷰에 메인뷰 셀 적용
  Ting/Search/SearchVC.swift
  Ting/Search/SearchView.swift
Labels: implement, feat

#55 Feat : PostDetailVC/ReportVC 디자인수정 + RadioButton파일 삭제
  Ting/Post/PostDetailVC.swift
  Ting/Post/RadioButton.swift
  Ting/Post/ReportVC.swift
Labels: refactor

#62 Feat: 게시판리스트, 게시글 작성뷰 분리
  Ting/CustomView/BaseUploadView.swift
  Ting/CustomView/CustomTag.swift
  Ting/CustomView/LabelAndTagStackView.swift
  Ting/CustomView/LabelAndTextFieldView.swift
  Ting/Extension/AddArrangedSubviews.swift
  Ting/Extension/AddSubviews.swift
  Ting/Extension/HexColorCode.swift
  Ting/Post/FindMemberUploadVC.swift
  Ting/Post/FindMemberUploadView.swift
  Ting/Post/FindTeamUploadVC.swift
  Ting/Post/FindTeamUploadView.swift
  Ting/Post/PostListVC.swift
  Ting/Post/PostListView.swift
  Ting/Post/PostMainVC.swift
  Ting/Post/PostUploadVC.swift
  Ting/Post/PostUploadView.swift
  Ting/TabBar/TabBar.swift
Labels: implement, feat

#64 Refactor: MainView UI 수정
  Ting/Main/MainVC.swift
  Ting/Main/MainViewCell.swift
  Ting/MyPage/DeleteInfoVC.swift
  Ting/MyPage/EditInfoVC.swift
  Ting/MyPage/MyPageMainVC.swift
Labels: feat, refactor

#70 Refactor : 파일 폴더링 및 불필요 파일 삭제
  Ting/Main/MainView/MainVC.swift
  Ting/Main/MainView/MainViewCell.swift
  Ting/MyPage/MyPageView/DeleteInfoVC.swift
  Ting/MyPage/MyPageView/EditCustomView.swift
  Ting/MyPage/MyPageView/EditInfoVC.swift
  Ting/MyPage/MyPageView/MyPageCustomVIew.swift
  Ting/MyPage/MyPageView/MyPageMainVC.swift
  Ting/Post/PostView/FindMemberUploadVC.swift
  Ting/Post/PostView/FindMemberUploadView.swift
  Ting/Post/PostView/FindTeamUploadVC.swift
  Ting/Post/PostView/FindTeamUploadView.swift
  Ting/Post/PostView/PostDetailVC.swift
  Ting/Post/PostView/PostListVC.swift
  Ting/Post/PostView/PostListView.swift
  Ting/Post/PostView/ReportVC.swift
  Ting/Search/SearchView/SearchResultVC.swift
  Ting/Search/SearchView/SearchSelectModal.swift
  Ting/Search/SearchView/SearchSelectModalVC.swift
  Ting/Search/SearchView/SearchVC.swift
  Ting/Search/SearchView/SearchView.swift
  Ting/SignUp/SignUpView/PermissionVC.swift
  Ting/SignUp/SignUpView/PermissionView.swift
  Ting/SignUp/SignUpView/SignUpView.swift
  Ting/SignUp/SignUpView/SignUpViewController.swift
  Ting/SignUp/SignUpView/TermsCell.swift
  Ting/SignUp/SignUpView/TermsView.swift
  Ting/SignUp/SignUpView/TermsViewController.swift
  Ting/TabBar/TabBar.swift
  Ting/TestFile/TestModels/TestPost.swift
  Ting/TestFile/TestPostDetailVC.swift
  Ting/TestFile/TestPostMainVC.swift
  Ting/TestFile/TestPostUploadVC.swift
  Ting/TestFile/TestPostVC.swift
  Ting/TestFile/TestReportVC.swift
  Ting/TestFile/TestServices/TestPostService.swift
Labels: Warning, refactor
